FROM node:16.17-alpine as builder

#RUN mkdir -p /home/noe/app/node_modules && chown -R node:node/home/node/app

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3500

CMD [ "npm", "run", "start:dev" ]